## Lecture 16: Vectorizer and Vectorization

Given a corpus, C, normalize C, then vectorize C. --> Vocab and weights

Get vocab --> vocab is list of that appear in C.

Create a vector where each entry is a weight for item/vocab.

Corpus = ['Old macdonald had a farm, on his farm on had a cow. Old macdonald had a farm, on his farm had a pig. Old macdonald had a farm, on his farm he had a goat.']

normalize(corpus) --> Old, macdonald, farm, pig, cow, goat

Old, macdonald, farm, pig, cow, goat
[1, 1, 1, 0, 1, 0]
[1, 1, 1, 1, 0, 0]
[1, 1, 1, 0, 0, 1]

### N-grams
Vocabulary size can based on the n-gram

1-gram: Old, macdonald, farm, pig, cow, goat
2-gram: Old macdonald, macdonald farm, farm pig, pig cow, cow goat


## TF-IDF
term frequency - count of terms that appear in the document

document frequency - number of documents that contain term



In [1]:
! pipenv install scikit-learn

Installing scikit-learn...
Resolving scikit-learn...
Installing...
Adding scikit-learn to Pipfile's [packages] ...
✔ Installation Succeeded-learn...
⠏ Installing scikit-learn...
Pipfile.lock (6feff3) out of date, updating to (5653a4)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! Locking...
⠹ Locking...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (b0f9d322314520ab4c2308d6d4ba38c01cd983ce6a2337a34449768d005653a4)!
Installing dependencies from Pipfile.lock (5653a4)...


In [2]:
corpus = ['Old macdonald had a farm, on his farm on had a cow.', 
          'Old macdonald had a farm, on his farm had a pig.',
          'Old macdonald had a farm, on his farm he had a goat.']
corpus

['Old macdonald had a farm, on his farm on had a cow.',
 'Old macdonald had a farm, on his farm had a pig.',
 'Old macdonald had a farm, on his farm he had a goat.']

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
cv = CountVectorizer()
cv_matrix = cv.fit_transform(corpus)
cv_matrix

<3x10 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [5]:
cv_matrix.toarray()

array([[1, 2, 0, 2, 0, 1, 1, 1, 2, 0],
       [0, 2, 0, 2, 0, 1, 1, 1, 1, 1],
       [0, 2, 1, 2, 1, 1, 1, 1, 1, 0]])

In [7]:
vocab = cv.get_feature_names_out()

In [8]:
vocab

array(['cow', 'farm', 'goat', 'had', 'he', 'his', 'macdonald', 'old',
       'on', 'pig'], dtype=object)

In [9]:
import pandas as pd
df = pd.DataFrame(cv_matrix.toarray(), columns=vocab)

In [10]:
df

cow  farm  goat  had  he  his  macdonald  old  on  pig
0    1     2     0    2   0    1          1    1   2    0
1    0     2     0    2   0    1          1    1   1    1
2    0     2     1    2   1    1          1    1   1    0

In [12]:
cv_gram = CountVectorizer(ngram_range=(1,2))
cv_gram_matrix = cv_gram.fit_transform(corpus)

cv_gram_vocab = cv_gram.get_feature_names_out()
cv_gram_df = pd.DataFrame(cv_gram_matrix.toarray(), columns = cv_gram_vocab)
cv_gram_df

cow  farm  farm had  farm he  farm on  goat  had  had cow  had farm  \
0    1     2         0        0        2     0    2        1         1   
1    0     2         1        0        1     0    2        0         1   
2    0     2         0        1        1     1    2        0         1   

   had goat  ...  his  his farm  macdonald  macdonald had  old  old macdonald  \
0         0  ...    1         1          1              1    1              1   
1         0  ...    1         1          1              1    1              1   
2         1  ...    1         1          1              1    1              1   

   on  on had  on his  pig  
0   2       1       1    0  
1   1       0       1    1  
2   1       0       1    0  

[3 rows x 23 columns]

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

In [15]:
pipe = Pipeline(
steps = [('counter', CountVectorizer(binary = True)),
          ('tfidf', TfidfTransformer())
        ],
    memory = None
)

X  = pipe.fit_transform(corpus)

In [16]:
X.toarray()

array([[0.56860745, 0.33582872, 0.        , 0.33582872, 0.        ,
        0.33582872, 0.33582872, 0.33582872, 0.33582872, 0.        ],
       [0.        , 0.33582872, 0.        , 0.33582872, 0.        ,
        0.33582872, 0.33582872, 0.33582872, 0.33582872, 0.56860745],
       [0.        , 0.2919351 , 0.49428908, 0.2919351 , 0.49428908,
        0.2919351 , 0.2919351 , 0.2919351 , 0.2919351 , 0.        ]])

In [18]:
pipe['counter'].fit_transform(corpus).toarray()

array([[1, 1, 0, 1, 0, 1, 1, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
tf = TfidfVectorizer(binary = True)
X1 = tf.fit_transform(corpus)

In [22]:
X1.toarray()

array([[0.56860745, 0.33582872, 0.        , 0.33582872, 0.        ,
        0.33582872, 0.33582872, 0.33582872, 0.33582872, 0.        ],
       [0.        , 0.33582872, 0.        , 0.33582872, 0.        ,
        0.33582872, 0.33582872, 0.33582872, 0.33582872, 0.56860745],
       [0.        , 0.2919351 , 0.49428908, 0.2919351 , 0.49428908,
        0.2919351 , 0.2919351 , 0.2919351 , 0.2919351 , 0.        ]])

In [24]:
tf.get_feature_names_out()

array(['cow', 'farm', 'goat', 'had', 'he', 'his', 'macdonald', 'old',
       'on', 'pig'], dtype=object)

In [25]:
from sklearn import set_config

In [26]:
set_config(display = 'diagram')
display(pipe)
set_config(display = 'text')

Pipeline(steps=[('counter', CountVectorizer(binary=True)),
                ('tfidf', TfidfTransformer())])

In [32]:
vocab1 = list(tf.get_feature_names_out())

for i, c in enumerate(corpus):
    print(f'============ Document {i} ==============')
    for item in c.split(' '):
        try:
            idx = vocab1.index(item.lower())
        except:
            idx = -1
        
        print(idx, item, X1.toarray()[i][idx])

============ Document 0 ==============
7 Old 0.3358287187015034
6 macdonald 0.3358287187015034
3 had 0.3358287187015034
-1 a 0.0
-1 farm, 0.0
8 on 0.3358287187015034
5 his 0.3358287187015034
1 farm 0.3358287187015034
8 on 0.3358287187015034
3 had 0.3358287187015034
-1 a 0.0
-1 cow. 0.0
============ Document 1 ==============
7 Old 0.3358287187015034
6 macdonald 0.3358287187015034
3 had 0.3358287187015034
-1 a 0.5686074482205095
-1 farm, 0.5686074482205095
8 on 0.3358287187015034
5 his 0.3358287187015034
1 farm 0.3358287187015034
3 had 0.3358287187015034
-1 a 0.5686074482205095
-1 pig. 0.5686074482205095
============ Document 2 ==============
7 Old 0.2919350959760435
6 macdonald 0.2919350959760435
3 had 0.2919350959760435
-1 a 0.0
-1 farm, 0.0
8 on 0.2919350959760435
5 his 0.2919350959760435
1 farm 0.2919350959760435
4 he 0.49428908465833515
3 had 0.2919350959760435
-1 a 0.0
-1 goat. 0.0
